//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioHistorico
    {
        public int CodigoInventario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int StockAnterior { get; set; }
        public int StockNuevo { get; set; }
        public int PrecioUnitario { get; set; }
        public bool Ingreso { get; set; }
        public System.Guid UsuarioId { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
